name = "AbstractMediumProperties"
uuid = "62ded331-ac74-4432-90fd-7fafc84e95f4"
authors = ["Christian Haack <chr.hck@gmail.com>"]
version = "1.4.0"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
Polynomials = "4.0.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
